version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        # podés cambiar la versión de PHP si querés
        PHP_VERSION: "8.3"
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - laravel-vendor:/var/www/html/vendor
      - laravel-node_modules:/var/www/html/node_modules
    environment:
      # toman valores de tu .env local si existen
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8080}
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-laravel}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  web:
    image: nginx:1.27-alpine
    container_name: laravel-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel-db
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  queue:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_VERSION: "8.3"
    container_name: laravel-queue
    working_dir: /var/www/html
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    restart: unless-stopped
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      - app
      - db
      - redis
    volumes:
      - ./:/var/www/html
      - laravel-vendor:/var/www/html/vendor

  scheduler:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_VERSION: "8.3"
    container_name: laravel-scheduler
    working_dir: /var/www/html
    command: php artisan schedule:work
    restart: unless-stopped
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      - app
      - db
      - redis
    volumes:
      - ./:/var/www/html
      - laravel-vendor:/var/www/html/vendor

  # Vite para desarrollo (opcional)
  node:
    image: node:20-alpine
    container_name: laravel-node
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      # Vite debe apuntar a este host para HMR desde la app
      VITE_HOST: 0.0.0.0
    volumes:
      - ./:/var/www/html
      - laravel-node_modules:/var/www/html/node_modules
    depends_on:
      - app

volumes:
  mysql-data:
  redis-data:
  laravel-vendor:
  laravel-node_modules:
